.github/workflows/run_record_snapshots.yml
.github/workflows/run_version_bump.yml
.github/workflows/run_xcode_tests.yml
action_select_xcode_version/action.yml

feat: Xcode 14.2

---

.github/workflows/run_swiftlint.yml

Перенес содержимое swiftlint_ci.sh во флоу

NO-ISSUE: swiftlint flow

---

.github/workflows/run_swiftlint.yml

Добавил возможность указать кастомный путь до файла конфига. Параметр по умолчанию. Если параметр не указан , то конфиг будет искаться в корне

NO-ISSUE: Add custom config path

---

.github/workflows/run_swiftlint.yml

1. emoji reporter для лучшего понимания в чем проблема в логах джобы. Возможно, когда будет поддержка danger переделаем это
2. Из списка ошибок исключены todo (есть правило на TODO - линтер его подсвечивает как предупреждение). Локально это правило может работать (если включено), но на CI оно мешает, потому что обычно тудушки быстро не исправишь, а все предупреждения на CI расцениваются как ошибки
3. Линтер может проверять много таргетов и могла быть ситуация, что проверяется 3 таргета. В первом есть ошибки линтанга, а во 2 и 3 нет. Джоба не падает, потому что последняя проверка без ошибок. Теперь же падает. Полный список ошибок показывается в конце джобы

NO-ISSUE: Improvements

---

.github/workflows/run_swiftlint.yml

Убрал линтовку удаленных файлов. Придумал только такой способ. Нормально распарсить дифф хз как.

NO-ISSUE: Not lint deleted files

---

.github/documentation/DETEKT.md
.github/workflows/check_android_pr_with_detekt.yml

Вариант чека ПРа для андроид с запуском таски detekt.
Вынес в отдельный так как необходим только в андроид, а так же сам проект андроид должен быть [подготовлен](https://github.com/tutu-ru-mobile/android-user-space/pull/26) для его использования.

(NO-ISSUE) Добавлен воркфлоу для запуска detekt 

---

.github/workflows/run_android_ui_tests.yml

Обратная совместимость сохранена

(NO-ISSUE) Новые инпуты в воркфлоу для UI тестов андроид

---

.github/workflows/run_xcode_tests.yml

В некоторых местах сломалась выгрузка
дешевле убрать тут и поправить под единый вид в других местах

Убрал .xcresult

---

.github/workflows/run_xcode_tests.yml

Не выгружались артефакты, не трекалось время
Сейчас все работает корректно 
вот джоба, которая прошла корректно 
https://github.com/tutu-ru-mobile/checkout-ios/actions/runs/6309444101

NO-ISSUE. Поправил момент когда при падении тестов не проходили дальнейшие шаги джобы

---

.github/workflows/run_xcode_tests.yml

Архивируем .xcresult, чтобы сильно сократить время сохранения

NO-ISSUE: Optimize xcresult save

---

.github/workflows/check_pull_request.yml
.github/workflows/ios_check_pull_request.yml

Сделал отбельный воркфлоу дангера для iOS, который:
1. Скачивает централизованный `Dangerfile` ([ПР](https://github.com/tutu-ru-mobile/ProjectScripts/pull/1))
2. Позволяет инжектить путь до `Dangerfile`

MCORE-144: Shared dangerfile

---

.github/workflows/swift_check_pull_request.yml

- Вместо danger из докера берем локально установленные danger
- Обновил версию экшена чекаута до @v4. Хочу постепенно актуализировать все экшены, так как гитхаб уже ругается на использование устаревших

MCORE-481: Use local Danger

---

action_upload_to_artifactory/action.yml

new action for uploading to artifactory

feat: action for upload to artifactory

---

.github/workflows/run_danger_kotlin.yml
action_copy_config/Dangerfile.df.kts

1) добавлен MAVEN_READONLY_TOKEN для сборки 
2) обновлен Dangerfile, добавлено:
- проверка веток на соответствие шаблону
- проверка тайтлов на соответствие шаблону и наличие русского языка
- проверка описания ПР
Пример вывода можно увидеть в https://github.com/tutu-ru-mobile/android-user-space/pull/272

MCORE-516: update Dangerfile & workflow

---

.github/workflows/run_farm_xcode_tests.yml

[MCORE-586](https://hq.tutu.ru/browse/MCORE-586)-Добавить РЦ-шные сертификаты на ферму
Добавил серты через доп.параметр (не обязательный)

MCORE-586: Установка RC сертификата на симуляторы

---

.github/workflows/run_farm_emulator_android_ui_tests.yml
.github/workflows/run_ui_tests.yml

https://hq.tutu.ru/browse/MCORE-427

MCORE-427: запись скриншотов на ферме

---

.github/workflows/run_farm_emulator_android_ui_tests.yml
.github/workflows/run_ui_tests.yml

Добавила прогон аллюра, в случае если запущен не рекорд. Так же отсылается отбивка в ТГ.

MCORE-427: add support for allure results & tg reports

---

.github/workflows/run_farm_emulator_android_ui_tests.yml
.github/workflows/run_ui_tests.yml

Пофиксила условия для теста и добавила send_alert_to_tg как параметр.

MCORE-427: fix input & tests condition

---

.github/workflows/run_farm_emulator_android_ui_tests.yml
action_copy_config/Dangerfile.df.kts

– добавлен warn с номером задачи
– фикс ссылки на ПР при отбивке в ТГ

MCORE-655: add PR check

---

.github/workflows/run_danger_kotlin.yml
.github/workflows/run_security_scan.yml

- перевоз danger-kotlin на ферму
Вот тут сработало https://github.com/tutu-ru-mobile/android-foundation/actions/runs/10957562028/job/30425956745?pr=185#step:7:13

MCORE-685: run danger-kotlin on farm

---

.github/workflows/run_farm_emulator_android_ui_tests.yml

Добавила обработчик цикла, тк если внутри что-то отваливается, то ошибка не ломает билд (а это нам не надо)

MCORE-688: add handler for allure report
